import { CURRENT_ROLE } from "../../lib/current-role";

export type PublicKnowledgeCategory =
  | "current-role"
  | "career"
  | "research"
  | "project"
  | "faq";

export interface PublicKnowledgeEntry {
  slug: string;
  title: string;
  category: PublicKnowledgeCategory;
  content: string;
  summary?: string;
  source_refs: string[];
  reviewed_at: string;
  review_after?: string;
  visibility: "public";
  status: "reviewed";
}

// This is a deliberately small publication allowlist, not a repository inventory.
// Review content and provenance together before adding or changing an entry.
// Dates record the content review; they are not regenerated by an ingestion run.
const REVIEWED_AT = "2026-10-01";
const REVIEW_AFTER = "2026-12-30";
const PROFILE_SOURCE = "src/lib/professional-profile.ts";
const PROJECT_SOURCE = "src/components/ProjectShowcase.tsx";
const TIMELINE_URL = "https://dicoangelo.metaventionsai.com/#timeline";
const PROJECTS_URL = "https://dicoangelo.metaventionsai.com/#projects";

type ReviewedContent = Omit<
  PublicKnowledgeEntry,
  "reviewed_at" | "review_after" | "visibility" | "status"
>;

const reviewedContent: ReviewedContent[] = [
  {
    slug: "current-role-ezra",
    title: "Current role: Revenue Technology Manager at EZRA",
    category: "current-role",
    content: `Dico Angelo is ${CURRENT_ROLE.title} at ${CURRENT_ROLE.company}. He started on June 15, 2026 and works remotely from Toronto. ${CURRENT_ROLE.description}

His responsibilities include: ${CURRENT_ROLE.highlights.join("; ")}.

These are role responsibilities, not a claim that every initiative is completed or has a measured business outcome. Revenue forecasting ownership, SaaS revenue ownership and hyperscaler co-sell responsibilities are not part of the verified description of this role. Cloud-alliance and marketplace achievements belong to his earlier Contentsquare role. Metaventions AI is concurrent independent work.`,
    source_refs: ["src/lib/current-role.ts", PROFILE_SOURCE, TIMELINE_URL],
  },
  {
    slug: "career-contentsquare",
    title: "Contentsquare: partner systems, marketplace operations and attribution",
    category: "career",
    content: "Dico worked at Contentsquare from May 2023 to November 2025. His title of record was Sr. Partner Systems and Operations Specialist; Senior Partner Systems & Operations Lead is his public functional headline. On a three-person cloud alliance team, he ran systems administration and cloud marketplace deal-registration workflows. He supported Salesforce, AWS ACE, Microsoft Partner Center, Suger, PartnerStack, Crossbeam and Reveal; connected data and workflows; built reporting; and prepared regional enablement materials.\n\nThe team processed more than $800 million in shared pipeline total contract value across 2,500+ deal registrations with a 97% approval rate. This was registered pipeline, not personally generated sales or closed revenue. The marketplace program reached $30 million+ in revenue over 30 months; Dico contributed operations work. Program growth and Microsoft partner awards were team/company outcomes.\n\nHe supported partner incentive operations, co-managed AWS marketing development fund drawdown and supported train-the-trainer enablement. This does not establish ownership of alliance strategy, company-wide OneCRM architecture, quotas, compensation design or MDF payouts, or that he personally trained every seller.",
    source_refs: [PROFILE_SOURCE, TIMELINE_URL],
  },
  {
    slug: "career-rocket-mortgage-canada",
    title: "Rocket Mortgage Canada: product operations",
    category: "career",
    content: "Dico was a Product Operations Specialist at Rocket Mortgage Canada, formerly Edison Financial, from June 2020 to May 2023. This was one continuous employment period through the rebrand. He supported Salesforce data, reporting, document quality, onboarding and quality-control/evaluation workflows for a 45-agent operation. Supporting that operation does not mean he managed 45 direct reports. The reviewed profile does not establish precise savings or efficiency percentages for this work.",
    source_refs: [PROFILE_SOURCE, TIMELINE_URL],
  },
  {
    slug: "career-metaventions-ai",
    title: "Metaventions AI: concurrent independent founder work",
    category: "career",
    content: "Dico has run Metaventions AI as an independent founder practice since November 2025, alongside his current EZRA employment. He specifies systems in plain English, directs AI coding tools, and reviews, tests and deploys their output. His selected work includes ResearchGravity/Universal Cognitive Wallet for research capture and retrieval, career-workflow applications, SBC Inspector for configuration validation, and other prototypes. This is practical AI-assisted implementation experience; it does not establish unaided programming fluency or that each project is a commercial deployment. Metaventions AI is not his current employer in place of EZRA.",
    source_refs: [PROFILE_SOURCE, PROJECT_SOURCE, TIMELINE_URL],
  },
  {
    slug: "career-up2youth",
    title: "Up2Youth: founding director and program operations",
    category: "career",
    content: "Dico was Founding Director of Up2Youth from March 2019 to March 2022. The youth program was supported by a $255,000 grant over 36 months. He led program operations, community partnerships and grant reporting. The grant was program funding, not personal compensation or commercial revenue.",
    source_refs: [PROFILE_SOURCE, "src/components/CareerTimeline.tsx", "https://otf.ca/grants-awarded/5551", TIMELINE_URL],
  },
  {
    slug: "career-mentoring-community",
    title: "Mentoring and professional community participation",
    category: "career",
    content: "Dico volunteered as a Mass Fintech Hub mentor from January to April 2026, mentoring three students. He participated in Partnership Leaders Catalyst 2026 in New York City and Toronto. The reviewed profile establishes participation, not a speaker role or an endorsement by those organizations.",
    source_refs: [PROFILE_SOURCE, TIMELINE_URL],
  },
  {
    slug: "faq-education-training",
    title: "Education and training",
    category: "faq",
    content: "Dico holds a Bachelor of Business Administration in Marketing from the University of Windsor's Odette School of Business. The reviewed public profile does not specify a graduation year. Training and course completions should be described as training; they are not professional certifications unless individually verified as such.",
    source_refs: [PROFILE_SOURCE, TIMELINE_URL],
  },
  {
    slug: "project-career-board",
    title: "Career Board: AI-assisted career workflows",
    category: "project",
    content: "Career Board is a career-workflow web application for résumé review and role comparison. Its public /try demo uses sample inputs and does not require signup. It was built through AI-assisted development, review and testing. Hiring-panel personas are simulations that support exploration, not real employer decisions or hiring guarantees. The reviewed portfolio lists Next.js, React, TypeScript and Tailwind in the application stack. The broader profile also refers to career-workflow work as CareerCoach Antigravity; Career Board is the name of the currently featured public demo.",
    source_refs: [PROJECT_SOURCE, PROFILE_SOURCE, "https://careers.metaventionsai.com/try", PROJECTS_URL],
  },
  {
    slug: "project-partnership-graph",
    title: "Partnership Graph: illustrative partner-intelligence concept",
    category: "project",
    content: "Partnership Graph is a concept demo for partner intelligence. A dashboard and Model Context Protocol (MCP) interface explore partner health, co-sell workflows and attribution using illustrative data. The concept relates to Dico's partner-systems and operations background. It is not a commercial deployment or a live CRM integration, and the named platforms and partners are unaffiliated. The demo's sample partner information is not evidence of actual customers, partnerships or revenue.",
    source_refs: [PROJECT_SOURCE, PROFILE_SOURCE, "https://partnerships.metaventionsai.com", PROJECTS_URL],
  },
  {
    slug: "project-sbc-inspector",
    title: "SBC Inspector / SBC-AutoOps: configuration review prototype",
    category: "project",
    content: "SBC Inspector, also presented as SBC-AutoOps, is a configuration-validation prototype for supported session border controller formats. It combines deterministic checks, plain-English explanations and a Model Context Protocol (MCP) inspection interface. Its findings support human review before deployment; they do not guarantee a safe configuration, universal vendor coverage or production readiness. The implementation was directed and reviewed using AI coding tools. The portfolio currently provides a project description rather than a verified working public demo link.",
    source_refs: [PROJECT_SOURCE, PROFILE_SOURCE, PROJECTS_URL],
  },
  {
    slug: "project-researchgravity",
    title: "ResearchGravity: research capture and retrieval",
    category: "project",
    content: "ResearchGravity provides research capture and retrieval tools with a FastAPI backend, vector search and a Model Context Protocol (MCP) interface. It organizes session notes, source URLs and findings so prior work can be retrieved and reviewed. The reviewed portfolio lists Qdrant among its technologies. This describes the research workflow and implementation, not independently measured retrieval accuracy or a guarantee that errors are prevented. No private notebook contents, research-session details or inventory counts are part of this public description.",
    source_refs: [PROJECT_SOURCE, PROFILE_SOURCE, "src/app/showcase/data.ts", PROJECTS_URL],
  },
  {
    slug: "project-universal-cognitive-wallet",
    title: "Universal Cognitive Wallet (UCW): cross-platform context",
    category: "project",
    content: "Universal Cognitive Wallet (UCW) is a cross-platform research capture and retrieval project. It normalizes captured AI session records, stores searchable context and explores relationships between records, with access through MCP tools. The reviewed portfolio lists PostgreSQL and pgvector. Coverage depends on configured integrations. Similarity between records is a retrieval aid, not proof of independent discovery or cognition. The public portfolio does not establish comprehensive capture of every AI interaction or publish the contents of private captured sessions.",
    source_refs: [PROJECT_SOURCE, PROFILE_SOURCE, PROJECTS_URL],
  },
  {
    slug: "project-frontier-alpha",
    title: "Frontier Alpha: investment research prototype",
    category: "project",
    content: "Frontier Alpha is an experimental interface for exploring factor exposure, portfolio scenarios and AI-assisted investment research. It demonstrates a research workflow rather than verified investment results. The reviewed description does not claim validated forecasting accuracy, investment performance or autonomous trading capability.",
    source_refs: [PROJECT_SOURCE, "https://frontier-alpha.metaventionsai.com", PROJECTS_URL],
  },
  {
    slug: "research-burstiness-lp4fm-2026",
    title: "Burstiness: accepted NeurIPS 2026 LP4FM workshop poster",
    category: "research",
    content: "Dico Angelo coauthored \"Burstiness Was Measured Wrong, and Prompting Cannot Aim It\" with Vittoria Lanzo. Submission #114 received an \"Accept (Poster)\" decision for Linguistic Principles for Foundation Models (LP4FM), a NeurIPS 2026 workshop. The decision was confirmed by the OpenReview notification dated September 29, 2026. The public record is https://openreview.net/forum?id=1E20ig92Zi.\n\nThe work studies sentence-length rhythm in generated language. The reviewed portfolio describes Dico's contribution as research tooling, experiment infrastructure, data workflows and reproducibility checks. Burstiness Engine was the earlier project working title. The verified status is an accepted workshop paper/poster, not a NeurIPS main-track paper or oral presentation. Author order, an already-delivered presentation, archival publication and a DOI are not established by the reviewed acceptance record.",
    source_refs: [PROFILE_SOURCE, PROJECT_SOURCE, "src/components/CareerTimeline.tsx", "https://openreview.net/forum?id=1E20ig92Zi"],
  },
  {
    slug: "faq-professional-focus",
    title: "What is Dico's professional focus?",
    category: "faq",
    content: "Dico's professional focus is revenue technology and go-to-market (GTM) operations. He connects platforms, improves operational workflows, supports tool adoption and applies AI to practical problems. His experience combines current revenue-technology responsibilities at EZRA, prior partner and cloud-marketplace operations at Contentsquare, product operations at Rocket Mortgage Canada, and concurrent independent AI-assisted projects. This profile does not establish responsibility for every part of revenue strategy or ownership of sales quotas.",
    source_refs: [PROFILE_SOURCE, "src/lib/current-role.ts", "https://dicoangelo.metaventionsai.com"],
  },
  {
    slug: "faq-ai-assisted-build-method",
    title: "How does Dico build and evaluate AI-assisted systems?",
    category: "faq",
    content: "Dico specifies systems in plain English, directs AI coding tools, then reviews, tests and deploys their output. His public projects provide examples of workflow design and practical AI-assisted implementation. This does not mean every project is production-ready or that all code was written without assistance. Repository sizes, code counts, internal self-assessment scores and illustrative dashboard values are not independent evidence of technical proficiency, reliability or business impact. Tool vendors listed on the site are technologies used, not clients or endorsements.",
    source_refs: [PROFILE_SOURCE, PROJECT_SOURCE, PROJECTS_URL],
  },
  {
    slug: "faq-research-authorship-evidence",
    title: "Which research is Dico's, and what evidence is supported?",
    category: "faq",
    content: "The reviewed coauthored research is \"Burstiness Was Measured Wrong, and Prompting Cannot Aim It\", accepted as a poster at the NeurIPS 2026 LP4FM workshop with Vittoria Lanzo. Other papers referenced in implementation projects remain work by their named authors; studying or implementing a paper does not establish authorship.\n\nPhilip Drammeh's arXiv paper 2511.15755 was withdrawn on August 31, 2026 following a code audit. Its withdrawn Decision Quality, zero-variance and actionability results are not valid evidence of project effectiveness. Historical implementations of that scoring idea do not establish that it is validated. Frontier-operations scores on the portfolio are informal self-assessments, not independent certifications.",
    source_refs: [PROFILE_SOURCE, "https://openreview.net/forum?id=1E20ig92Zi", "https://arxiv.org/abs/2511.15755"],
  },
  {
    slug: "faq-contact",
    title: "How can someone contact Dico?",
    category: "faq",
    content: "Dico's public contact email is dico.angelo97@gmail.com. His LinkedIn profile is https://www.linkedin.com/in/dico-angelo/ and his portfolio is https://dicoangelo.metaventionsai.com. He is based in Toronto. Contact him directly for opportunities, collaboration or details that are not established in the reviewed public profile.",
    source_refs: [PROFILE_SOURCE, "https://www.linkedin.com/in/dico-angelo/", "https://dicoangelo.metaventionsai.com/#contact"],
  },
  {
    slug: "faq-location-work-authorization",
    title: "Location and work-authorization questions",
    category: "faq",
    content: "Dico is a Canadian citizen working remotely from Toronto in his current EZRA role. The reviewed public profile does not establish present U.S. work authorization or unconditional eligibility for a particular visa. Specific immigration, relocation and work-authorization questions need confirmation directly from Dico.",
    source_refs: [PROFILE_SOURCE, "src/lib/current-role.ts", "https://dicoangelo.metaventionsai.com/#contact"],
  },
];

export const PUBLIC_KNOWLEDGE_ENTRIES: PublicKnowledgeEntry[] = reviewedContent.map(
  (entry) => ({
    ...entry,
    reviewed_at: REVIEWED_AT,
    review_after: REVIEW_AFTER,
    visibility: "public",
    status: "reviewed",
  })
);

/** Compact, deterministic fallback when the reviewed database is unavailable. */
export function getPublicKnowledgeContext(): string {
  return PUBLIC_KNOWLEDGE_ENTRIES.map((entry) => {
    const publicSources = entry.source_refs.filter((source) => source.startsWith("https://"));
    return [
      `## ${entry.title}`,
      entry.content,
      `Reviewed: ${entry.reviewed_at}`,
      `Public sources: ${publicSources.join("; ")}`,
    ].join("\n");
  }).join("\n\n");
}
